### PR TITLE
Implement batchtools

### PR DESCRIPTION
**Pull request by jakob-r**

### CODE REVIEW

**Comment by berndbischl** [comment]
I cannot merge this until bt is on CRAN?
Or can you add a mechinism so we can include packages which are only on github?

**Comment by jakob-r** [comment]
I don't fully understand why appveyor failed. It exceeded one hour? For this one test run?

**Comment by jakob-r** [comment]
First there was a problem because RSQLite was too old so i wanted to take the chance to switch to container structure but now it can not find `mpi.h` although it OpenMPI seems to be successfully installed and exported.
Need help.

**Comment by mllg** [comment]
Quick solution: Don't do containers but install apt packages (see batchtools' .travis.yml):

```
sudo: required
dist: trusty
language: r

r:
  - oldrel
  - release
  - devel

addons:
  apt:
    packages:
      - r-cran-rmpi
      - libssh2-1-dev

after_success:
  - Rscript -e 'library(covr);coveralls()'
```

**Comment by mllg** [comment]
Merged into branch

**Comment by jakob-r** [comment]
You mean you work on it here: https://github.com/berndbischl/parallelMap/tree/jakob-r-feature_batchtools
So I will close it here to avoid confusion

**Pull request closed without merging**
